# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: hill law jazz limb penalty escape public dish stand bracket blue jar

compiler:
  solc:
    version: 0.8.0

console:
  show_colors: true

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
